[package]
edition = "2021"
name = "robot-arm"
version = "0.1.0"

[[bin]]
name = "robot-arm"
path = "./src/bin/main.rs"

[dependencies]
common = { path = "../common" }
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32c6"] }
esp-hal = { version = "=1.0.0-rc.0", features = ["esp32c6", "unstable"] }
esp-alloc = "0.8.0"
esp-println = { version = "0.11.0", features = ["esp32c6"] }
